// <auto-generated />
using System;
using Exo02_Hotel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exo02_Hotel.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250205143910_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Exo02_Hotel.Models.Chambre", b =>
                {
                    b.Property<int>("NumeroChambre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumeroChambre"));

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("NombreLits")
                        .HasColumnType("int");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("StatutChambre")
                        .HasColumnType("int");

                    b.Property<decimal>("Tarif")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)");

                    b.HasKey("NumeroChambre");

                    b.HasIndex("HotelId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Chambres");

                    b.HasData(
                        new
                        {
                            NumeroChambre = 101,
                            NombreLits = 2,
                            StatutChambre = 0,
                            Tarif = 100m
                        },
                        new
                        {
                            NumeroChambre = 102,
                            NombreLits = 3,
                            StatutChambre = 1,
                            Tarif = 150m
                        },
                        new
                        {
                            NumeroChambre = 103,
                            NombreLits = 2,
                            StatutChambre = 0,
                            Tarif = 100m
                        },
                        new
                        {
                            NumeroChambre = 201,
                            NombreLits = 4,
                            StatutChambre = 2,
                            Tarif = 200m
                        },
                        new
                        {
                            NumeroChambre = 202,
                            NombreLits = 2,
                            StatutChambre = 0,
                            Tarif = 100m
                        },
                        new
                        {
                            NumeroChambre = 203,
                            NombreLits = 3,
                            StatutChambre = 1,
                            Tarif = 150m
                        });
                });

            modelBuilder.Entity("Exo02_Hotel.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Exo02_Hotel.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("Exo02_Hotel.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("StatutReservation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("HotelId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Exo02_Hotel.Models.Chambre", b =>
                {
                    b.HasOne("Exo02_Hotel.Models.Hotel", null)
                        .WithMany("Chambres")
                        .HasForeignKey("HotelId");

                    b.HasOne("Exo02_Hotel.Models.Reservation", null)
                        .WithMany("Chambres")
                        .HasForeignKey("ReservationId");
                });

            modelBuilder.Entity("Exo02_Hotel.Models.Client", b =>
                {
                    b.HasOne("Exo02_Hotel.Models.Hotel", null)
                        .WithMany("Clients")
                        .HasForeignKey("HotelId");
                });

            modelBuilder.Entity("Exo02_Hotel.Models.Reservation", b =>
                {
                    b.HasOne("Exo02_Hotel.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exo02_Hotel.Models.Hotel", null)
                        .WithMany("Reservations")
                        .HasForeignKey("HotelId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Exo02_Hotel.Models.Hotel", b =>
                {
                    b.Navigation("Chambres");

                    b.Navigation("Clients");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Exo02_Hotel.Models.Reservation", b =>
                {
                    b.Navigation("Chambres");
                });
#pragma warning restore 612, 618
        }
    }
}
